@simpleauthapi_HostAddress = http://localhost:5248
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSm_Do28iLCJleHAiOjE3NTQ3NzE0NDJ9.2yA_x0QilNrk4_tdp1rXu9HFVl4SOJRZkTFOlT4wsvE
###

POST {{simpleauthapi_HostAddress}}/login
Content-Type: application/json

{
    "username": "João"
}

###

GET {{simpleauthapi_HostAddress}}/clients/
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{simpleauthapi_HostAddress}}/products/
Accept: application/json
Authorization: Bearer {{token}}
