name: Build and Push Docker image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./simpleauthapi
          file: ./simpleauthapi/Dockerfile
          push: false
          tags: simpleauthapi:latest

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker image
        run: |
          docker build -t simpleauthapi:latest -f ./simpleauthapi/Dockerfile ./simpleauthapi

      - name: Tag and push Docker image
        run: |
          docker tag simpleauthapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/simpleauthapi:latest
          docker